[package]
name = "ndarray-test"
version = "0.1.0"
authors = ["Matz Haugen <matz.haugen@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
rand = "0.8.0"
